#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

clear
# INSTALAR BSPWM ARCH LINUX
echo -e ${blueColour}'\n   Instalando Utilidades'${endColour}
echo -e ${greenColour}'\n   Vamos a instalar estos programas:'${endColour}
echo -e ${yellowColour}'
sudo pacman -Sy git wget tilix rofi p7zip file-roller thunar gedit vlc compton  feh  net-tools --noconfirm
sudo pacman -Sy firefox firefox-i18n-es-es --noconfirm
sudo pacamn -Sy chromium --noconfirm \n'${endColour}
read -p "Press enter para continuar"
sudo pacman -Sy git wget tilix rofi p7zip file-roller thunar gedit vlc compton  feh  net-tools --noconfirm
sudo pacman -Sy firefox firefox-i18n-es-es --noconfirm
sudo pacman -Sy chromium --noconfirm
clear

# Instalando bspwm
echo -e ${blueColour}'\n  Instalando bspwm'${endColour}
echo -e ${greenColour}'\n   Vamos a instalar estos programas:'${endColour}
echo -e ${yellowColour}'
sudo pacman -Sy bspwm sxhkd -noconfirm
\n'${endColour}
read -p "Press enter para continuar"
sudo pacman -Sy bspwm sxhkd -noconfirm
clear

# Instalando el Display Manager (D.M) gestor de inicio de sesion - Activando
echo -e ${blueColour}'\n  Instalando el Display Manager (D.M) gestor de inicio de sesion - Activando'${endColour}
echo -e ${greenColour}'\n   Instalamos el inicio de sesion y lo activamos:'${endColour}
echo -e ${yellowColour}'
sudo pacman -Sy lightdm lightdm-gtk-greeter -noconfirm
systemctl enable lightdm.service
\n'${endColour}
read -p "Press enter para continuar"
sudo pacman -Sy lightdm lightdm-gtk-greeter -noconfirm
systemctl enable lightdm.service
clear

# Configurando el escritorio bspwm
echo -e ${blueColour}'\n   Configurando el escritorio bspwm'${endColour}
echo -e ${greenColour}'\n   Configuramos el bspwm copiando las carpetas y dando permisos:'${endColour}
echo -e ${yellowColour}'
mkdir -p ~/.config/{bspwm,sxhkd}
cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/
cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
chmod u+x ~/.config/bspwm/bspwmrc
touch ~/.xinitrc
cp -r ~/arch/bspwm//bspwm ~/.config
cp -r ~/arch/bspwm//sxhkd ~/.config
\n'${endColour}
read -p "Press enter para continuar"
mkdir -p ~/.config/{bspwm,sxhkd}
cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/
cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
chmod u+x ~/.config/bspwm/bspwmrc
touch ~/.xinitrc
cp -r ~/arch/bspwm//bspwm ~/.config
cp -r ~/arch/bspwm//sxhkd ~/.config
clear

# Configuramos el compton
echo -e ${blueColour}'\n   # Configuramos el compton'${endColour}
echo -e ${greenColour}'\n   Creamos el script resize para añadir ventanas y configuramos compton:'${endColour}
echo -e ${yellowColour}'
mkdir .config/bspwm/scripts
touch .config/bspwm/scripts/bspwm_resize
chmod +x .config/bspwm/scripts/bspwm_resize
mkdir ~/.config/compton
touch ~/.config/compton/compton.conf
cp -r ~/arch/bspwm//compton ~/.config
\n'${endColour}
read -p "Press enter para continuar"
mkdir .config/bspwm/scripts
touch .config/bspwm/scripts/bspwm_resize
chmod +x .config/bspwm/scripts/bspwm_resize
mkdir ~/.config/compton
touch ~/.config/compton/compton.conf
cp -r ~/arch/bspwm//compton ~/.config
clear

# poniendo el fondo de pantalla
echo -e ${blueColour}'\n   Poniendo el fondo de pantalla'${endColour}
echo -e ${greenColour}'\n   Añadimos la carpeta Wallapers para tener fondo pantalla:'${endColour}
echo -e ${yellowColour}'
cp -r ~/arch/Wallapers/ ~/Imágenes/Wallapers
\n'${endColour}
read -p "Press enter para continuar"
cp -r ~/arch/Wallapers/ ~/Imágenes/Wallapers
clear

# Instalar y configurar polybar
echo -e ${blueColour}'\n   Instalar y configurar polybar'${endColour}
echo -e ${greenColour}'\n   Durante la instalacion del polybar "podemos ir a tomar cafe"\n nos va a pedir el password de usuario,\n si se pasa el tienpo y no poneis el password hay que instalar de nuevo.\n Lo podeis hacer despues del rienicio.'${endColour}
echo -e ${yellowColour}'
yay -Sy polybar-git -noconfirm
mkdir ~/.config/polybar
cp /usr/share/doc/polybar/config ~./config/polybarf
touch ~/.config/polybar/launch.sh
chmod +x ~/.config/polybar/launch.sh
sudo cp -r ~/arch/bspwm/Hack /usr/share/fonts/
cp -r ~/arch/bspwm//polybar ~/.config
\n'${endColour}
read -p "Press enter para continuar"
yay -Sy polybar-git -noconfirm
mkdir ~/.config/polybar
cp /usr/share/doc/polybar/config ~./config/polybarf
touch ~/.config/polybar/launch.sh
chmod +x ~/.config/polybar/launch.sh
sudo cp -r ~/arch/bspwm/Hack /usr/share/fonts/
cp -r ~/arch/bspwm//polybar ~/.config
clear

# Crear modulo de red
echo -e ${blueColour}'\n   Crear modulo de red'${endColour}
echo -e ${greenColour}'\n   Para que os muestre la ip del pc, introducimos el comando: ifconfig\n 
Nos indicara el modulo de red por ej: '${redColour}enp0s3${endColour}'\n
En la carpeta bin que creamos teneis que cambiar el modulo por el vuestro\n
En los dos archivos ethernet'${endColour}
echo -e ${yellowColour}'
mkdir ~/.config/bin
touch ~/.config/bin/ethernet_status.sh
chmod +x ~/.config/bin/ethernet_status.sh
\n'${endColour}
read -p "Press enter para continuar"
mkdir ~/.config/bin
touch ~/.config/bin/ethernet_status.sh
chmod +x ~/.config/bin/ethernet_status.sh
clear

# Creando nuestro modulo de VPN:
echo -e ${blueColour}'\n   Creando nuestro modulo de VPN'${endColour}
echo -e ${greenColour}'\n   Creamos el archivo para la VPN'${endColour}
echo -e ${yellowColour}'
touch ~/.config/bin/vpnstatus.sh
chmod +x ~/.config/bin/vpnstatus.sh
cp -r ~/arch/bspwm//bin ~/.config
\n'${endColour}
read -p "Press enter para continuar"
touch ~/.config/bin/vpnstatus.sh
chmod +x ~/.config/bin/vpnstatus.sh
cp -r ~/arch/bspwm//bin ~/.config
clear

# Instalar bloqueo de pantalla:
echo -e ${blueColour}'\n   Instalar bloqueo de pantalla'${endColour}
echo -e ${greenColour}'\n   Instalamos el bloqueo de pantalla, se activa con:\n
ctrl + super + alt + b\n
Se desbloquea poniendo al password de usuario.'${endColour}
echo -e ${yellowColour}'
sudo pacman -Sy i3lock imagemagick -noconfirm
\n'${endColour}
read -p "Press enter para continuar"
sudo pacman -Sy i3lock imagemagick -noconfirm
clear


# detalle_titulo:
echo -e ${blueColour}'\n   Titulo'${endColour}
echo -e ${greenColour}'\n   instruccion'${endColour}
echo -e ${yellowColour}'
Cuerpo
\n'${endColour}
comando$
read -p "Press enter para continuar"
clear